server:
  port: 8080

spring:
  application:
    name: meetube-api-server
  datasource:
    url: jdbc:postgresql://${ENV_RDB_HOST}:${ENV_RDB_PORT}/${ENV_RDB_DATABASE}
    username: ${ENV_RDB_USER}
    password: ${ENV_RDB_PASSWORD}
    hikari:
      connection-timeout: 300000
      connection-test-query: select 1
      idle-timeout: 60000
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 30
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: debug